
name: Build

on:
  push:
    branches:
      - flutter-*-webos
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: hemanth2808/new_image2:withsysandold

    strategy:
      matrix:
        arch: [arm]
        mode: [release]
        include:
          - arch: arm
            triple: arm-linux-gnueabi

    env:
      OUTPUT_NAME: linux_${{ matrix.mode }}_${{ matrix.arch }}

    steps:
     
    - name: Free Disk Space (Ubuntu)
      uses: actions/checkout@v2
      with:
       
        tool-cache: true
        
             
       
    - uses: actions/checkout@v3
      with:
          path: src/flutter
          fetch-depth: 0
    - name: install depot_tools
      run: |
          echo ${{ github.ref_name }}
          git clone --depth=1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$PWD/depot_tools" >> $GITHUB_PATH

      
      
    - name: gclient sync
      run: |
         
          gclient config --name=src/flutter --unmanaged https://github.com/Hemanth518-debug/engine      
          gclient sync  -v --no-history --shallow

    - name: verify formatting
      if: matrix.arch == 'arm' && matrix.mode == 'release'
      working-directory: src/flutter
      run: |
          
          git remote add origin https://github.com/flutter-webOS/engine.git
          
          ci/format.sh
    - name: verify formatting2 
      working-directory: src
      run: |
           gclient sync -D
    - name: build
      run: |
        
          echo "beforegn"
          src/flutter/tools/gn --target-sysroot /flutter/sysroot/o20-sysroot-for-flutter/lib32-recipe-sysroot --target-toolchain /flutter/llvm-project/build/toolchain --target-triple arm-starfishmllib32-linux-gnueabi --linux-cpu arm --runtime-mode release --embedder-for-target --no-lto --target-os linux --arm-float-abi softfp --disable-desktop-embeddings
          echo "aftergn"
          ninja -C src/out/linux_release_arm -j 32
          echo "afterninja"
         
    - uses: actions/upload-artifact@v3
      with:
          name: webos-${{ matrix.arch }}-${{ matrix.mode }}
          path: src/out/${{ env.OUTPUT_NAME }}/libflutter_*.so
          if-no-files-found: error

    - uses: actions/upload-artifact@v3
      if: github.event_name == 'push'
      with:
          name: webos-${{ matrix.arch }}-${{ matrix.mode }}_symbols
          path: src/out/${{ env.OUTPUT_NAME }}/so.unstripped/libflutter_*.so
          if-no-files-found: error

    - uses: actions/upload-artifact@v3
      if: matrix.mode != 'debug'
      with:
          name: webos-${{ matrix.arch }}-${{ matrix.mode }}_linux-x64
          path: src/out/${{ env.OUTPUT_NAME }}/clang_x64/gen_snapshot
          if-no-files-found: error

     
